<?php

return [
    'role_structure' => [

        'superadmin' => [
            'users'          => 'c,r,u,d,p',
            'states'          => 'c,r,u,d,p',
            'trips'          => 'c,r,u,d,p',
            'attachments'          => 'c,r,u,d,p',
            'employees' => 'c,r,u,d,p',
            'bills' => 'c,r,u,d,p',
            'accounts' => 'c,r,u,d,p',
            'customers' => 'c,r,u,d,p',
            'credits' => 'c,r,u,d,p',
            'employees' => 'c,r,u,d,p',
            'expenses' => 'c,r,u,d,p',
            'groups' => 'c,r,u,d,p',
            'invoices' => 'c,r,u,d,p',
            'items' => 'c,r,u,d,p',
            'roles' => 'c,r,u,d,p',
            'stores' => 'c,r,u,d,p',
            'suppliers' => 'c,r,u,d,p',
            'transactions' => 'c,r,u,d,p',
            'salaries' => 'c,r,u,d,p',
            'units' => 'c,r,u,d,p',
            'payments' => 'c,r,u,d,p',
            'charges' => 'c,r,u,d,p',
            'cheques' => 'c,r,u,d,p',
            'expenses' => 'c,r,u,d,p',
            'transfers' => 'c,r,u,d,p',
            'safes' => 'c,r,u,d,p',
            'collaborators' => 'c,r,u,d,p',
            'entries' => 'c,r,u,d,p',
            'reports' => 'r',
            'sms' => 'rec',
            'drivers' => 'c,r,u,d',
            'orders' => 'c,r,u,d',
            'settings' => 'c,r,u,d',
            'cars' => 'c,r,u,d',
            'expenses-type' => 'c,r,u,d',
        ],

    ],
    'permission_structure' => [
        'superadmin' => [
            'users'   => 'c,r,u,d,p',
            'users'          => 'c,r,u,d,p',
            'trips'          => 'c,r,u,d,p',
            'attachments'          => 'c,r,u,d,p',
            'employees' => 'c,r,u,d,p',
            'bills' => 'c,r,u,d,p',
            'accounts' => 'c,r,u,d,p',
            'customers' => 'c,r,u,d,p',
            'credits' => 'c,r,u,d,p',
            'employees' => 'c,r,u,d,p',
            'expenses' => 'c,r,u,d,p',
            'transfers' => 'c,r,u,d,p',
            'safes' => 'c,r,u,d,p',
            'collaborators' => 'c,r,u,d,p',
            'entries' => 'c,r,u,d,p',
            'reports' => 'r',
            'groups' => 'c,r,u,d,p',
            'invoices' => 'c,r,u,d,p',
            'items' => 'c,r,u,d,p',
            'roles' => 'c,r,u,d,p',
            'stores' => 'c,r,u,d,p',
            'suppliers' => 'c,r,u,d,p',
            'transactions' => 'c,r,u,d,p',
            'salaries' => 'c,r,u,d,p',
            'units' => 'c,r,u,d,p',
            'payments' => 'c,r,u,d,p',
            'charges' => 'c,r,u,d,p',
            'cheques' => 'c,r,u,d,p',
            'expenses' => 'c,r,u,d,p',
            'categories' => 'c,r,u,d',
            'settings' => 'c,r,u,d',
            'drivers' => 'c,r,u,d',
            'sms' => 'rec',
            'cars' => 'c,r,u,d',
            'expenses-type' => 'c,r,u,d',
        ],
    ],


    'permissions_map' => [
        'c' => 'create',
        'r' => 'read',
        'u' => 'update',
        'd' => 'delete',
        'p' => 'print',
        'rec' => 'receive'
    ]
];
